/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Cards: typeof import('./src/components/Home/Cards.vue')['default']
    ClassMentalityForm: typeof import('./src/components/forms/class-mentality-form.vue')['default']
    CourseContent: typeof import('./src/components/Home/CourseContent.vue')['default']
    CourseContentExpansion: typeof import('./src/components/Home/CourseContentExpansion.vue')['default']
    Depositions: typeof import('./src/components/Home/Depositions.vue')['default']
    FAQ: typeof import('./src/components/Home/FAQ.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IntroCall: typeof import('./src/components/mentality/intro-call.vue')['default']
    IntroContents: typeof import('./src/components/mentality/intro-contents.vue')['default']
    Introduction: typeof import('./src/components/Home/Introduction.vue')['default']
    IntroProfessor: typeof import('./src/components/mentality/intro-professor.vue')['default']
    IntroSection: typeof import('./src/components/mentality/intro-section.vue')['default']
    MaterialContent: typeof import('./src/components/Home/MaterialContent.vue')['default']
    Phrase1: typeof import('./src/components/Home/Phrase1.vue')['default']
    Professor: typeof import('./src/components/mentality/professor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaleSection: typeof import('./src/components/Home/SaleSection.vue')['default']
    SaleSectionPacks: typeof import('./src/components/Home/SaleSectionPacks.vue')['default']
    Warrant7days: typeof import('./src/components/Home/Warrant7days.vue')['default']
  }
}
