/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/curso/[curso]': RouteRecordInfo<'/curso/[curso]', '/curso/:curso', { curso: ParamValue<true> }, { curso: ParamValue<false> }>,
    '/links': RouteRecordInfo<'/links', '/links', Record<never, never>, Record<never, never>>,
    '/mentalidade': RouteRecordInfo<'/mentalidade', '/mentalidade', Record<never, never>, Record<never, never>>,
    '/pagina-em-andamento': RouteRecordInfo<'/pagina-em-andamento', '/pagina-em-andamento', Record<never, never>, Record<never, never>>,
    '/sobre-nos': RouteRecordInfo<'/sobre-nos', '/sobre-nos', Record<never, never>, Record<never, never>>,
  }
}
